### ISSUE TITLE
UnitConversionError encountered when running getnoise_list

### ISSUE THREAD

**Issue by AstroRipples** [AlecThomson/RACS-tools#22]
Testing out `getnoise_list.py` on a MeerKAT polarisation cube. I've constructed Q and U frequency cubes using `WSclean` which I've convolved to a common resolution and stacked into a RA / Dec / freq cube. On trying to run `getnoise_list` I encounter a UnitConversionError:

```
$ python3 getnoise_list.py --file bad_channels_chan512.txt --ncores 32 RMSynth_chan512/qcube.fits RMSynth_chan512/ucube.fits
Checking Q: 100%|█████████████████████████████████| 443/443 [00:01<00:00, 286.68it/s]
Traceback (most recent call last):
  File "/homes/riseley/.local/lib/python3.9/site-packages/astropy/units/quantity.py", line 890, in to_value
    scale = self.unit._to(unit)
  File "/homes/riseley/.local/lib/python3.9/site-packages/astropy/units/core.py", line 1093, in _to
    raise UnitConversionError(
astropy.units.core.UnitConversionError: 'Unit("Jy / beam")' is not a scaled version of 'Unit(dimensionless)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/homes/riseley/.local/lib/python3.9/site-packages/astropy/units/quantity.py", line 1248, in __float__
    return float(self.to_value(dimensionless_unscaled))
  File "/homes/riseley/.local/lib/python3.9/site-packages/astropy/units/quantity.py", line 893, in to_value
    value = self._to_value(unit, equivalencies)
  File "/homes/riseley/.local/lib/python3.9/site-packages/astropy/units/quantity.py", line 800, in _to_value
    return self.unit.to(unit, self.view(np.ndarray),
  File "/homes/riseley/.local/lib/python3.9/site-packages/astropy/units/core.py", line 1130, in to
    return self._get_converter(Unit(other),
  File "/homes/riseley/.local/lib/python3.9/site-packages/astropy/units/core.py", line 1061, in _get_converter
    raise exc
  File "/homes/riseley/.local/lib/python3.9/site-packages/astropy/units/core.py", line 1046, in _get_converter
    return self._apply_equivalencies(
  File "/homes/riseley/.local/lib/python3.9/site-packages/astropy/units/core.py", line 1022, in _apply_equivalencies
    raise UnitConversionError(
astropy.units.core.UnitConversionError: 'Jy / beam' and '' (dimensionless) are not convertible

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/work/riseley/software/RACS-tools/racs_tools/getnoise_list.py", line 330, in <module>
    cli()
  File "/local/work/riseley/software/RACS-tools/racs_tools/getnoise_list.py", line 324, in cli
    main(pool, args)
  File "/local/work/riseley/software/RACS-tools/racs_tools/getnoise_list.py", line 214, in main
    totalbad = getbadchans(
  File "/local/work/riseley/software/RACS-tools/racs_tools/getnoise_list.py", line 123, in getbadchans
    qnoisevals = np.array(qnoisevals)
  File "/homes/riseley/.local/lib/python3.9/site-packages/astropy/units/quantity.py", line 1250, in __float__
    raise TypeError('only dimensionless scalar quantities can be '
TypeError: only dimensionless scalar quantities can be converted to Python scalars

```

As a quick sanity check I removed the Jy/beam `BUNIT` from the Q/U-cube headers but that immediately threw an error when I tried running `getnoise_list` so it seems to be a required keyword.

**Comment by AlecThomson** [comment]
Solved with #23
